version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    volumes:
      - /mnt/d/nagaraj/csvserver/solution/inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env
